name: check qa status

on:
  pull_request:
  workflow_dispatch:
  issue_comment:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          echo event number ${{ github.event.number }}
          echo event issue number ${{ github.event.issue.number }}
          echo ${{ toJson(github.event) }}
      - uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.number || github.event.issue.number }}
          body-includes: qa
      - run: |
          echo ${{ steps.fc.outputs.comment-id }}

      - name: A/B Check
        if: ${{ steps.fc.outputs.comment-id == '' }}
        run: |
          echo "::error title=missing qa ok"
          exit 1

      - name: Report tests check
        if: ${{ steps.fc.outputs.comment-id != '' }}
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.checks.create({
              name: 'qa comment check name',
              head_sha: '${{ github.event.issue.pull_request.head.sha }}',
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'qa comment check title',
                summary: 'Results: success'
              },
              owner: context.repo.owner,
              repo: context.repo.repo
            })