name: check qa status

on:
  pull_request:
  workflow_dispatch:
  issue_comment:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          echo event number ${{ github.event.number }}
          echo event issue number ${{ github.event.issue.number }}
      - uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.number || github.event.issue.number }}
          body-includes: qa
      - name: A/B Check
        if: ${{ steps.fc.outputs.comment-id }} == ''
        run: |
          echo "::error title=missing qa ok"
          exit 1

      - name: A/B Check2
        if: ${{ steps.fc.outputs.comment-id }} == null
        run: |
          echo "::error title=missing qa ok 2"
          exit 1
