name: check qa status

on:
  pull_request:
  workflow_dispatch:
  issue_comment:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.number || github.event.issue.number }}
          body-includes: qa
      - run: |
          echo ${{ steps.fc.outputs.comment-id }}

      - name: A/B Check
        if: ${{ steps.fc.outputs.comment-id == '' }}
        run: |
          echo "::error title=missing qa ok"
          exit 1

      - name: get pullrequest head sha
        id: get-sha
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            console.log('${{ github.event.number || github.event.issue.number }}')
            const prId = 4;  // Replace with your pull request ID
            const query = `
              query($owner: String!, $repo: String!, $pullNumber: Int!) {
                repository(owner: $owner, name: $repo) {
                  pullRequest(number: $pullNumber) {
                    title
                    body
                    state
                    author {
                      login
                    }
                    createdAt
                    updatedAt
                    url
                    headRef {
                      name
                    }
                  }
                }
              }`;
            const variables = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pullNumber: prId,
            };

            const response = await github.graphql(query, variables);
            console.log(response.repository.pullRequest);

      - run: echo "${{ steps.get-sha.outputs.result }}"

      - name: Report tests check
        if: ${{ steps.fc.outputs.comment-id != '' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.checks.create({
              name: 'qa comment check name',
              head_sha: '${{ steps.get-sha.outputs.result }}',
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'qa comment check title',
                summary: 'Results: success'
              },
              owner: context.repo.owner,
              repo: context.repo.repo
            })